import "./globals.css";
import { Providers } from "./Providers";
import { Ubuntu } from "next/font/google";
import Image from "next/image";
import pic from "../public/bg.jpg";

const inter = Ubuntu({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          alt="background"
          src={pic}
          width={0}
          height={0}
          className="fixed -z-20 min-h-screen min-w-full bg-contain"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
